name: coZBit

gereksiz:
   author: "Nick Lugovskoy"
   email: "lugovksoy@gmail.com"
   domain: "cozbit.com"
   analytics: "UA-49163162-1"
   disqus: "lugovskoy"

markdown: redcarpet
permalink: p/:title
pygments: true
exclude: [README.md, LICENSE, Makefile]
