name: coZBit

gereksiz:
   author: "Nick Lugovskoy"
   email: "lugovksoy@gmail.com"
   domain: "cozbit.com"
   analytics: "UA-15818219-8"
   disqus: "cozbit"

markdown: redcarpet
permalink: /:year/:title
pygments: true
exclude: [README.md, LICENSE, Makefile]
