name: Bugs of Berk

gereksiz:
   author: "Berk Özbalcı"
   email: "berkozbalci@gmail.com"
   domain: "bugsofberk.net"
   analytics: "UA-49163162-1"
   disqus: "bugsofberk"

markdown: redcarpet
permalink: p/:title
pygments: true
exclude: [README.md, LICENSE, Makefile]
